name: Deploy

on:
  push:
    branches:
      - master
      - deploy
    paths-ignore:
      - README.md

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Run Unit tests
        run: npm run test:ci

      - name: Cypress run Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm run preview
          wait-on: 'http://127.0.0.1:4173/'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
